import type { ReaderCssPreset } from '../types';

export const BUILTIN_VINTAGE_PARCHMENT_BUTTERFLY_ID = 'builtin-vintage-parchment-butterfly';

const VINTAGE_PARCHMENT_BUTTERFLY_CSS = [
  '/* ═══ 复古羊皮纸 · 幻蝶主题 ═══ */',
  '',
  '/* 引入思隐宋体 (正文) */',
  '@import url("https://fontsapi.zeoseven.com/892/main/result.css");',
  '/* 引入英文手写体 (落款) */',
  '@import url("data:text/css,%40font-face%7Bfont-family%3A%22ZSFT-dd%22%3Bsrc%3Aurl(%22https%3A%2F%2Ffontsapi.zeoseven.com%2Fdd%2Fmain.woff2%22)%20format(%22woff2%22)%3Bfont-style%3Anormal%3Bfont-weight%3A400%3Bfont-display%3Aswap%3B%7D");',
  '',
  '/* 在这里自定义落款内容(\\A 代表换行，请保留首尾的双引号) */',
  ':root {',
  '  --sh-signature-text: "Penned in reverie, \\A Whispers of Time";',
  '}',
  '',
  '/* ─── 动画定义 ─── */',
  '@keyframes sh-paper-shimmer {',
  '  0%   { background-position: 50% 50%, 0 0, 0 0, 0 0; }',
  '  50%  { background-position: 52% 52%, 0 0, 0 0, 0 0; }',
  '  100% { background-position: 50% 50%, 0 0, 0 0, 0 0; }',
  '}',
  '',
  '@keyframes sh-butterfly-flutter {',
  '  0%   { transform: translate(0, 0) rotate(75deg) scale(1); filter: drop-shadow(2px 4px 6px rgba(60, 40, 20, 0.3)); }',
  '  25%  { transform: translate(1px, -2px) rotate(73deg) scale(1.02); filter: drop-shadow(3px 5px 7px rgba(60, 40, 20, 0.35)); }',
  '  50%  { transform: translate(0, -3px) rotate(77deg) scale(1.04); filter: drop-shadow(2px 7px 8px rgba(60, 40, 20, 0.4)); }',
  '  75%  { transform: translate(-1px, -1px) rotate(74deg) scale(1.01); filter: drop-shadow(2px 5px 6px rgba(60, 40, 20, 0.35)); }',
  '  100% { transform: translate(0, 0) rotate(75deg) scale(1); filter: drop-shadow(2px 4px 6px rgba(60, 40, 20, 0.3)); }',
  '}',
  '',
  '/* ─── 纸张外容器 ─── */',
  '.sh-paper {',
  '  border-radius: 0 !important;',
  '  transition: box-shadow 0.5s cubic-bezier(0.2, 0.8, 0.2, 1), transform 0.5s cubic-bezier(0.2, 0.8, 0.2, 1) !important;',
  '',
  '  background:',
  '    radial-gradient(',
  '      ellipse 90% 70% at center,',
  '      rgba(255, 252, 240, 0.6) 0%,',
  '      rgba(230, 210, 180, 0.1) 60%,',
  '      rgba(180, 150, 110, 0.3) 100%',
  '    ),',
  '    linear-gradient(rgba(248, 240, 225, 0.88), rgba(248, 240, 225, 0.88)),',
  '    url("https://i.postimg.cc/5t0M8ck0/p-new0120-m-new01205.png") repeat,',
  '    linear-gradient(135deg, #f3ead3 0%, #e8dcc4 100%) !important;',
  '',
  '  background-size: 150% 150%, auto, 160px 160px, auto !important;',
  '  background-blend-mode: normal, normal, multiply, normal;',
  '  animation: sh-paper-shimmer 20s ease-in-out infinite !important;',
  '  border: 1px solid rgba(139, 90, 43, 0.3) !important;',
  '',
  '  box-shadow:',
  '    inset 0 0 50px rgba(139, 90, 43, 0.1),',
  '    inset 0 1px 3px rgba(255, 255, 255, 0.6),',
  '    0 2px 8px rgba(0, 0, 0, 0.1) !important;',
  '  position: relative;',
  '  overflow: visible !important;',
  '  margin-top: 30px !important;',
  '}',
  '',
  '/* Hover 态：更明显的悬浮抬起效果 */',
  '.sh-paper:hover {',
  '  transform: translateY(-5px) !important;',
  '  box-shadow:',
  '    inset 0 0 50px rgba(139, 90, 43, 0.1),',
  '    inset 0 1px 3px rgba(255, 255, 255, 0.6),',
  '    0 22px 35px -5px rgba(0, 0, 0, 0.2),',
  '    0 12px 15px -6px rgba(0, 0, 0, 0.12) !important;',
  '}',
  '',
  '/* 蝴蝶贴纸：右上角 */',
  '.sh-paper::after {',
  "  content: '';",
  '  position: absolute;',
  '  top: -25px;',
  '  right: -25px;',
  '  width: 80px;',
  '  height: 80px;',
  '  opacity: 0.9;',
  '  pointer-events: none;',
  '  z-index: 10;',
  '  animation: sh-butterfly-flutter 5s ease-in-out infinite;',
  '  background-image: url("https://i.postimg.cc/B6j4fWTq/HTC-Heritage-Library-Butterflies-Element-12.png");',
  '  background-size: contain;',
  '  background-repeat: no-repeat;',
  '}',
  '',
  '/* ─── 纸张内层 (含落款) ─── */',
  '.sh-paper-inner {',
  '  padding-top: 8px;',
  '  padding-bottom: 65px !important;',
  '  position: relative;',
  '}',
  '',
  '/* 复古英文信件落款 */',
  '.sh-paper-inner::after {',
  '  content: var(--sh-signature-text);',
  '  white-space: pre;',
  '  position: absolute;',
  '  bottom: 20px;',
  '  right: 20px;',
  '  font-family: "ZSFT-dd", cursive;',
  '  font-size: 1.00rem;',
  '  color: #5c3f20;',
  '  opacity: 0.7;',
  '  text-align: right;',
  '  line-height: 1.2;',
  '  transform: rotate(-3deg);',
  '  pointer-events: none;',
  '  text-shadow: 1px 1px 2px rgba(139, 90, 43, 0.1);',
  '}',
  '',
  '/* ─── 编辑器整体 ─── */',
  '.studyhub-note-editor {',
  "  color: #3b2e24 !important;",
  "  font-family: 'SiyinSong', 'Noto Serif SC', 'Source Han Serif CN', serif !important;",
  '}',
  '',
  '/* ─── H1 居中与复古外框 ─── */',
  '.studyhub-note-editor h1 {',
  '  text-align: center !important;',
  '  color: #4a2e15 !important;',
  '  font-size: 1.55rem !important;',
  '  padding: 8px 15px !important;',
  '  margin-bottom: 16px !important;',
  '  background: rgba(139, 90, 43, 0.06) !important;',
  '  border: 3px double rgba(139, 90, 43, 0.45) !important;',
  '  border-radius: 2px !important;',
  '}',
  '',
  '.studyhub-note-editor h2 {',
  '  color: #5c3f20 !important;',
  '  font-size: 1.28rem !important;',
  '  border-bottom: 1px dashed rgba(139, 90, 43, 0.25);',
  '  padding-bottom: 4px;',
  '  margin-top: 1.5em !important;',
  '}',
  '',
  '.studyhub-note-editor h3 {',
  '  color: #6b4d2a !important;',
  '  font-size: 1.15rem !important;',
  '  margin-top: 1.2em !important;',
  '}',
  '',
  '/* ─── 正文 ─── */',
  '.studyhub-note-editor p {',
  '  color: #3b2e24;',
  '  line-height: 1.85;',
  '}',
  '',
  '/* ─── 粗体 ─── */',
  '.studyhub-note-editor strong {',
  '  color: #201205 !important;',
  '  font-weight: bold !important;',
  '  text-shadow: 0 0 0.5px rgba(43, 29, 18, 0.2);',
  '  position: relative;',
  '  display: inline-block;',
  '  text-decoration: none !important;',
  '}',
  '',
  '.studyhub-note-editor strong::after {',
  "  content: '';",
  '  position: absolute;',
  '  left: 0;',
  '  bottom: -2px;',
  '  width: 100%;',
  '  height: 2px;',
  '  background: linear-gradient(90deg, transparent 0%, rgba(139, 90, 43, 0.6) 15%, rgba(139, 90, 43, 0.6) 85%, transparent 100%);',
  '  pointer-events: none;',
  '}',
  '',
  '/* ─── 斜体 ─── */',
  '.studyhub-note-editor em {',
  '  color: #786045 !important;',
  '  font-style: italic;',
  "  font-family: 'Georgia', serif;",
  '}',
  '',
  '/* ─── 列表 ─── */',
  '.studyhub-note-editor ul,',
  '.studyhub-note-editor ol {',
  '  padding-left: 1.4rem !important;',
  '}',
  '',
  '.studyhub-note-editor ul {',
  '  list-style-type: none !important;',
  '}',
  '',
  '.studyhub-note-editor ul li {',
  '  position: relative;',
  '  margin: 8px 0 !important;',
  '  color: #3b2e24;',
  '}',
  '',
  '.studyhub-note-editor ul li::before {',
  "  content: '';",
  '  position: absolute;',
  '  left: -1.35rem;',
  '  top: 0.4rem;',
  '  width: 0.95rem;',
  '  height: 0.95rem;',
  '  background-image: url("https://i.postimg.cc/Gt3PmQmW/HTC-Heritage-Library-Butterflies-Element-6.png");',
  '  background-size: contain;',
  '  background-repeat: no-repeat;',
  '  opacity: 0.8;',
  '  filter: sepia(0.3);',
  '}',
  '',
  '.studyhub-note-editor ol {',
  '  color: #4a3a2a;',
  '}',
  '',
  '.studyhub-note-editor ol li {',
  '  margin: 8px 0 !important;',
  '  color: #3b2e24;',
  '}',
  '',
  '/* ═══════════════════════════════ */',
  '/* 暗色模式                        */',
  '/* ═══════════════════════════════ */',
  '',
  '.dark-mode .sh-paper {',
  '  background:',
  '    radial-gradient(',
  '      ellipse 90% 70% at center,',
  '      rgba(80, 70, 55, 0.3) 0%,',
  '      rgba(40, 30, 20, 0.7) 80%,',
  '      rgba(25, 18, 12, 0.9) 100%',
  '    ),',
  '    linear-gradient(rgba(36, 28, 22, 0.92), rgba(36, 28, 22, 0.92)),',
  '    url("https://i.postimg.cc/5t0M8ck0/p-new0120-m-new01205.png") repeat,',
  '    linear-gradient(135deg, #2a2218 0%, #3a3022 100%) !important;',
  '',
  '  background-blend-mode: normal, normal, soft-light, normal;',
  '  border-color: rgba(180, 150, 100, 0.15) !important;',
  '  box-shadow:',
  '    inset 0 0 60px rgba(0, 0, 0, 0.5),',
  '    inset 0 1px 3px rgba(80, 65, 40, 0.1),',
  '    0 3px 10px rgba(0, 0, 0, 0.4) !important;',
  '}',
  '',
  '.dark-mode .sh-paper:hover {',
  '  transform: translateY(-5px) !important;',
  '  box-shadow:',
  '    inset 0 0 60px rgba(0, 0, 0, 0.5),',
  '    inset 0 1px 3px rgba(80, 65, 40, 0.1),',
  '    0 22px 35px rgba(0, 0, 0, 0.6),',
  '    0 12px 15px -4px rgba(0, 0, 0, 0.5) !important;',
  '}',
  '',
  '/* 暗色蝴蝶 */',
  '.dark-mode .sh-paper::after {',
  '  opacity: 0.7;',
  '  animation: sh-butterfly-flutter-dark 5s ease-in-out infinite;',
  '}',
  '',
  '@keyframes sh-butterfly-flutter-dark {',
  '  0%   { transform: translate(0, 0) rotate(75deg) scale(1); filter: drop-shadow(2px 4px 6px rgba(0, 0, 0, 0.7)) brightness(0.7) sepia(0.4); }',
  '  25%  { transform: translate(1px, -2px) rotate(73deg) scale(1.02); filter: drop-shadow(3px 5px 7px rgba(0, 0, 0, 0.75)) brightness(0.7) sepia(0.4); }',
  '  50%  { transform: translate(0, -3px) rotate(77deg) scale(1.04); filter: drop-shadow(2px 7px 8px rgba(0, 0, 0, 0.8)) brightness(0.7) sepia(0.4); }',
  '  75%  { transform: translate(-1px, -1px) rotate(74deg) scale(1.01); filter: drop-shadow(2px 5px 6px rgba(0, 0, 0, 0.75)) brightness(0.7) sepia(0.4); }',
  '  100% { transform: translate(0, 0) rotate(75deg) scale(1); filter: drop-shadow(2px 4px 6px rgba(0, 0, 0, 0.7)) brightness(0.7) sepia(0.4); }',
  '}',
  '',
  '/* 暗色模式下：手写落款调整为浅金底色 */',
  '.dark-mode .sh-paper-inner::after {',
  '  color: #c5b497;',
  '  opacity: 0.5;',
  '  text-shadow: 1px 1px 2px rgba(0, 0, 0, 0.3);',
  '}',
  '',
  '.dark-mode .studyhub-note-editor {',
  '  color: #c0b29a !important;',
  '}',
  '',
  '.dark-mode .studyhub-note-editor h1 {',
  '  color: #decba8 !important;',
  '  background: rgba(180, 150, 100, 0.08) !important;',
  '  border-color: rgba(160, 130, 90, 0.4) !important;',
  '}',
  '',
  '.dark-mode .studyhub-note-editor h2 {',
  '  color: #d6c4a8 !important;',
  '  border-bottom-color: rgba(180, 150, 100, 0.15);',
  '}',
  '',
  '.dark-mode .studyhub-note-editor h3 {',
  '  color: #c5b497 !important;',
  '}',
  '',
  '.dark-mode .studyhub-note-editor p {',
  '  color: #c0b29a;',
  '}',
  '',
  '.dark-mode .studyhub-note-editor strong {',
  '  color: #eaddc5 !important;',
  '  text-shadow: 0 0 1px rgba(0,0,0,0.5);',
  '}',
  '',
  '.dark-mode .studyhub-note-editor strong::after {',
  '  background: linear-gradient(90deg, transparent 0%, rgba(180, 150, 100, 0.6) 15%, rgba(180, 150, 100, 0.6) 85%, transparent 100%);',
  '}',
  '',
  '.dark-mode .studyhub-note-editor em {',
  '  color: #a89880 !important;',
  '}',
  '',
  '/* 暗色模式下：统一列表文字颜色 */',
  '.dark-mode .studyhub-note-editor ol,',
  '.dark-mode .studyhub-note-editor ul li,',
  '.dark-mode .studyhub-note-editor ol li {',
  '  color: #c0b29a !important;',
  '}',
  '',
  '/* 暗色模式下：无序列表蝴蝶图标反相调色 */',
  '.dark-mode .studyhub-note-editor ul li::before {',
  '  opacity: 0.85;',
  '  filter: invert(85%) sepia(15%) hue-rotate(350deg) brightness(1.1) !important;',
  '}',
  '',
  '.sh-note-placeholder {',
  '  font-size: 0 !important;',
  '}',
  '.sh-note-placeholder::before {',
  "  content: '笔墨留香...';",
  '  font-size: 0.875rem;',
  "  font-family: 'SiyinSong', serif;",
  '  color: rgba(139, 90, 43, 0.35);',
  '  font-style: italic;',
  '}',
  '.dark-mode .sh-note-placeholder::before {',
  '  color: rgba(180, 150, 100, 0.3);',
  '}',
].join('\n');

export const DEFAULT_PAPER_CSS_PRESETS: ReaderCssPreset[] = [
  {
    id: BUILTIN_VINTAGE_PARCHMENT_BUTTERFLY_ID,
    name: '复古羊皮纸 · 幻蝶',
    css: VINTAGE_PARCHMENT_BUTTERFLY_CSS,
  },
];
